import autogen
from autogen import AssistantAgent, UserProxyAgent


# Set API Endpoint
config_list_gpt4 = autogen.config_list_from_json(
    "OAI_CONFIG_LIST",
    filter_dict={
        "model": ["gpt-4", "gpt-4-0314", "gpt4", "gpt-4-32k", "gpt-4-32k-0314", "gpt-4-32k-v0314"],
    },
)

# Configure LLM Parameters
llm_config = {"config_list": config_list_gpt4, "seed": 42, "engine": "goptee-giantbrain"}

user_proxy = autogen.UserProxyAgent(
    name="User_proxy",
    system_message="A human admin.",
    code_execution_config={"last_n_messages": 3, "work_dir": "groupchat"},
    human_input_mode="NEVER",
)

coder = autogen.AssistantAgent(
    name="Coder",  # the default assistant agent is capable of solving problems with code
    llm_config=llm_config,
)

critic = autogen.AssistantAgent(
    name="Critic",
    system_message="""Critic. You are a helpful assistant highly skilled in evaluating the quality of computational linguistics code by providing a score from 1 (bad) - 10 (good) while providing clear rationale. YOU MUST CONSIDER COMPUTATIONAL LINGUISTICS BEST PRACTICES for each evaluation. Specifically, you can carefully evaluate the code across the following dimensions
- bugs (bugs):  are there bugs, logic errors, syntax error or typos? Are there any reasons why the code may fail to compile? How should it be fixed? If ANY bug exists, the bug score MUST be less than 5.
- Data transformation (transformation): Is the data transformed appropriately for the transcription type? E.g., does the data represent appropriately extracted and transformed and sensible, coherent output?
- Goal compliance (compliance): how well the code meets the specified goals?
- Analysis type (type): CONSIDERING BEST PRACTICES, is the transcription of high enough quality given it's source? Is there another transcription approach that would be more effective at capturing high quality transcriptions? If a different approach is more appropriate, the score MUST BE LESS THAN 5.

YOU MUST PROVIDE A SCORE for each of the above dimensions.
{bugs: 0, transformation: 0, compliance: 0, type: 0}
Do not suggest code.
Finally, based on the critique above, suggest a concrete list of actions that the coder should take to improve the code.
""",
    llm_config=llm_config,
)

groupchat = autogen.GroupChat(agents=[user_proxy, coder, critic], messages=[], max_round=20)
manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config)

## START CHAT


user_proxy.initiate_chat(
    manager,
    message=""
    "Can you help me source, evaluate and transcribe videos from YouTube "
    "and convert them into a format that will be suitable for training our gpt-4 deployment in Azure? "
    "If you scan this folder, you will see that yuo have made several attempts, but none have worked. "
    "Please start in the groupchat folder. You will find your previous download_videos.py file, "
    "Along with the video_lins.csv file. "
    "I need you to produce for me a working deliverable. If you have questions, just ask me. "
    "Note that the last time you worked on this, you delivered code with errors, this is not acceptable. "
    "Here is the error that was generated by download_videos.py: "
    "ERROR: youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug ."
    "ERROR: Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update."
    "ERROR: Be sure to call youtube-dl with the --verbose flag and include its complete output."
    "First, you will need to search for the best matching video URL, in each of these cases, "
    "You will search for videos from the @wharton channel on YouTube, then you will "
    "Construct a csv file containing the title of the video and the name. "
    "If you don't find a match, that's ok. Create the entry in the csv anyway, "
    "But set the url to http://# "
    "Here are the topics we want to find and transcribe. "
    "Scaling a Business: How to Build a Unicorn "
    "Technology Acceleration "
    "Driving Strategic Innovation: Leading Complex Initiatives for Impact "
    "Product Management and Strategy "
    "Leading a Technology-Driven Organization "
    "Executive Presence and Influence: Persuasive Leadership Development "
    "Corporate Governance: Maximize Your Effectiveness in the Boardroom "
    "CTO Strategic Mindset: Responding to Change and Creating Change "
    "Frameworks and Building Blocks "
    "Generating and Evaluating Commercial Ideas "
    "Entry Strategies "
    "Strategic Adaptation and Renewal "
    "Ecosystems "
    "Machine Learning "
    "The AI Stack and Competitive Implications "
    "Blockchain and Cryptocurrencies "
    "Technology Policy "
    "Global Technology Trends "
    "Environmental, Social, and Governance (ESG) Essentials for a New Business Era "
    "Scaling "
    "Metrics "
    "Leading Innovation "
    "Process View of Innovation and Innovation Tournaments "
    "The CTO Perspective: Balancing External and Internal Modes of Innovation "
    "Accessing New Technologies and Platforms through Acquisition "
    "Once you have created this list, using the API key found in the youtube.txt file within this directory, "
    "you will proceed to download each of the videos. Along the way, you will save all scripts and notes in the folder, "
    "And leave them in place for reference once you have achieved your goals. "
    "Once downloaded, you will queue the videos up for transcription and execute a batch transcription job. "
    "You will then advise the critic that the videos have been transcribed "
    "And you will request the critical reviews the quality of your transcriptions "
    "Once video transcription quality is high enough for the critic, you will proceed to "
    "Prepare the transcripts for fine tuning a GPT-4 32k model within Azure. "
    "You will stop once you have completed a high qualiity train, test and validation data deliverables.",
)
# type exit to terminate the chat
